allowBuilds:
  core-js: false
minimumReleaseAgeExclude:
  - '@interop/data-integrity-proof@3.4.0'
  - '@interop/ed25519-signature@7.1.2'
  - '@interop/ezcap@7.2.1'
  - '@interop/http-digest-header@3.0.0'
  - '@interop/http-signature-zcap-invoke@6.2.3'
  - '@interop/storage-core@0.1.0'
  - '@interop/zcap@11.0.3'
  - '@interop/ecdsa-multikey@2.3.1'
  - '@interop/edv-client@17.2.0'
  - '@interop/minimal-cipher@7.4.0'
  - '@interop/x25519-key-agreement-key@5.1.0'
